blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=BroCodeOrganization.bro-code&ssr=false#review-details
      about: Enjoying Bro Code? Leave a review here!
